version: '3.8'

services:
  alpine-app:
    container_name: alpine-app
    build:
      context: .
      dockerfile: alpine.dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ./:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:maria-db
    user: vscode
    depends_on:
      - maria-db
  maria-db:
    container_name: maria-db
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret45678
      MYSQL_USER: user
      MYSQL_PASSWORD: secret1234
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  php-server:
    container_name: php-fundamentals
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - '80:80'
    depends_on:
      - maria-db
  php-myadmin:
    container_name: myadmin-fundamentals
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST : maria-db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret45678
    depends_on:
      - maria-db
