USE curso_lunes;
SHOW TABLES;

-- DCL (Lenguaje de Control de Datos)
SELECT CURRENT_USER();

-- CREAR UN USUARIO
DROP USER IF EXISTS mylo@localhost;
CREATE USER mylo@localhost IDENTIFIED BY '1234';

-- OTORGAR PERMISOS DE LECTURA
GRANT SELECT ON curso_lunes.clientes TO mylo@localhost;
FLUSH PRIVILEGES;

-- ORTORGAR PERMISOS DE ESCRITURA
GRANT ALL PRIVILEGES ON curso_lunes.clientes TO mylo@localhost;
FLUSH PRIVILEGES;

-- VERIFICAR TODOS LOS USUARIOS DEL SERVIDOR
SELECT USER FROM mysql.user;
SELECT * FROM mysql.user;
SHOW DATABASES;

-- REMOVER TODOS LOS PRIVILEGIOS
REVOKE ALL PRIVILEGES ON curso_lunes.clientes FROM mylo@localhost;
FLUSH PRIVILEGES;

-- ELIMINAR USUARIO
DROP USER mylo@localhost;
FLUSH PRIVILEGES;